<?php

/**
 * Implements hook_user_insert().
 */
function wvu_login_user_insert(&$edit, $account, $category) {
  //if(isset($_SESSION) && $_SESSION['phpCAS']['attributes']['isstudent'])
    cas_user_operations_create_username(array($account->uid));
}

/**
 * Implements hook_cas_user_alter
*/
function wvu_login_cas_user_alter(&$cas_user){
    $user = user_load_by_name($cas_user['name']);
    if(!$user){ // username does not exist
      if($cas_user['attributes']['isstudent']=='FALSE'){ //user is not student - only students can log in
          $cas_user['login'] = FALSE;
      }
    }
    else cas_user_operations_create_username($cas_user['name']);
}


/**
 * Implements hook_page_build().

function wvu_login_page_build(&$page) {
    if(isset($_SESSION['phpCAS'])) dpm($_SESSION['phpCAS']);
}*/ 


/**
 * Implements hook_menu()).
*/
function wvu_login_menu() {
  $items = array();
  $items['wvulogout'] = array(
    'title' => 'Thanks for coming',
    'page callback' => '_wvu_login_logout',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_menu_alter(). Point the error pages to custom messages.
*/
function wvu_login_menu_alter(&$items) {
 
  $path = drupal_get_path('module', 'wvu_login') .'/';
  $items['elmsln/error/%'] = array(
    'title' => '',
    'title callback' => '_wvu_login_error_title',
    'title arguments' => array(2),
    'page callback' => '_wvu_login_error_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'weight' => 10,
    'type' => MENU_CALLBACK,
    'file' => $path.'wvu_login.errors.inc',
    );
 
  return $items;
} 

/**
 * Logout of CAS and redirect to....
 */
function _wvu_login_logout() {
  phpCAS::logout();
  return 'Thanks for coming';
}

?>