<?php

/**
 * Implements hook_user_insert().
 
function wvu_config_user_insert(&$edit, $account, $category) {
  cas_user_operations_create_username(array($account->uid));
}*/

/**
 * Implements hook_menu().
*/
function wvu_config_menu() {
  /*$items['wvulogout'] = array(
    'title' => 'Thanks for coming',
    'page callback' => '_wvu_config_logout',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );*/
  $items['wvuonline'] = array(
      'title' => 'WVU Online',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array('access content'),
      'page callback' => 'drupal_goto',
      'access callback' => TRUE,
      'page arguments' => array('http://online.wvu.edu'),
      'menu_name' => 'main-menu',
      'weight' => 8
    );

  return $items;
} 

/**
 * Implements hook_theme_registry_alter().
 */
function wvu_config_theme_registry_alter(&$theme_registry) {
   // Defined path to the current module.
  $module_path = drupal_get_path('module', 'wvu_config');
  // override main navigation template with custom template file within wvu_config module
  if(isset($theme_registry['cis_lmsless_bar'])){
      $theme_registry['cis_lmsless_bar']['theme path'] = $module_path . "/templates";
      $theme_registry['cis_lmsless_bar']['path'] = $module_path . "/templates";
      $theme_registry['cis_lmsless_bar']['type'] = "module";
      $theme_registry['cis_lmsless_bar']['template'] = "cis-lmsless-bar";
  }
  //dpm($theme_registry);
}

/**
 * Implements hook_page_build().
 */
function wvu_config_page_build(&$page) {
  //dpm($_SESSION['phpCAS']);
   $path = drupal_get_path('module', 'wvu_config') .'/';
   drupal_add_css('https://fast.fonts.net/cssapi/36d8cd92-7cc7-499b-b169-0eed9d670283.css',array('type'=>'exteral'));
   drupal_add_css($path . 'css/wvu_config.css'); 
}

/**
 * Logout of CAS and redirect to....
 
function _wvu_config_logout() {
  // to stuff
  return '';
}*/

/**
 * Implements hook_page_build().

function wvu_config_aanda_page_build(&$page) {
  $path = drupal_get_path('module', 'wvu_config') .'/';
  drupal_add_css($path . 'css/pattern.css');
  drupal_add_css($path . 'css/wvu_config.css');
}
 */
/**
 * Implements hook_cis_service_instance_options_alter().

function wvu_config_cis_service_instance_options_alter(&$options, $course, $service) {
  // ensure this module gets hooked into future builds
  $options['en'][] = 'wvu_config';
  $options['en'][] = 'cas';
  $staff = array('li', 'bob');

  foreach ($staff as $member) {
    $options['ucrt'][] = $member . ' --mail=' . $member . '@wvu.edu';
    $options['urol']['staff'][] =  $member;
  }

  // add admin member roles to site
  $admins = array('eugene');
  foreach ($admins as $admin) {
    $options['urol']['administrator'][] = $admin;
  }
} */

/**
 * Implements hook_cis_service_instance_job_file_alter().
 
function wvu_config_cis_service_instance_job_file_alter(&$content, $course, $service, $service_instance) {
  // may seem odd but double running cron can prime syncing
  $content .= 'drush dis bakery' . "\n";
}*/
